port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
proxies:
  - name: SG Trojan-WS(2025-02-02)
    server: 104.26.7.171
    port: 443
    type: trojan
    password: 375feb10-db47-11ef-841e-1239d0255272
    skip-cert-verify: true
    sni: sg3.socifiles.com
    network: ws
    ws-opts:
      path: /trojanws
      headers:
        Host: sg3.socifiles.com
    udp: true
  - name: SG Vless-WS(2025-02-01)
    server: 104.26.7.171
    port: 443
    type: vless
    uuid: faf00d10-db33-11ef-b18c-1239d0255272
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: sg3.socifiles.com
    network: ws
    ws-opts:
      path: /vlws
      headers:
        Host: sg3.socifiles.com
    udp: true
  - name: 443 Vmess Singapore HE-1 Limit 2025-01-30
    server: 104.26.7.171
    port: 443
    type: vmess
    uuid: 8b93c860-d8e4-11ef-b434-205c6d5f5d78
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: sg-1.hihu.net
    network: ws
    ws-opts:
      path: /5noqlk94
      headers:
        Host: sg-1.hihu.net
    udp: true
  - name: SG Trojan-WS
    server: 104.22.20.245
    port: 443
    type: trojan
    password: 375feb10-db47-11ef-841e-1239d0255272
    skip-cert-verify: true
    sni: asia1.fufo.org
    network: ws
    ws-opts:
      path: /trojanws
      headers:
        Host: asia1.fufo.org
    udp: true
proxy-groups:
  - name: ID-X
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - SG Trojan-WS(2025-02-02)
      - SG Vless-WS(2025-02-01)
      - 443 Vmess Singapore HE-1 Limit 2025-01-30
      - SG Trojan-WS

  - name: MIX-X
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - SG Trojan-WS(2025-02-02)
      - SG Vless-WS(2025-02-01)
      - 443 Vmess Singapore HE-1 Limit 2025-01-30
      - SG Trojan-WS
      
  - name: IKLAN
    type: select
    proxies:
     - MIX-X
     - REJECT

  - name: GAME
    type: select
    proxies:
     - ID-X
     - DIRECT
     - REJECT

rules:
 - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
 - RULE-SET,Block,IKLAN
 - RULE-SET,Game,GAME
 - RULE-SET,Umum,MIX-X
 - RULE-SET,indo,ID-X
 - RULE-SET,Sosmed,MIX-X
 - RULE-SET,Streaming,MIX-X
 - RULE-SET,Bankid,ID-X
 - RULE-SET,Tiktok,MIX-X
 - RULE-SET,Meta,MIX-X
 - RULE-SET,PortGame,GAME
 - MATCH,MIX-X


rule-providers:
  Game:
    type: file
    behavior: classical
    path: ./game.yaml 
  PortGame:
    type: file
    behavior: classical
    path: ./portgame.yaml
  Umum:
    type: file
    behavior: classical
    path: ./umum.yaml 
  indo:
    type: file
    behavior: classical
    path: ./indo.yaml
  Sosmed:
    type: file
    behavior: classical
    path: ./sosmed.yaml
  Streaming:
    type: file
    behavior: classical
    path: ./streaming.yaml
  Bankid:
    type: file
    behavior: domain
    path: ./bankid.yaml
  Tiktok:
    type: file
    behavior: domain
    path: ./tiktok.yaml
  Meta:
    type: file
    behavior: domain
    path: ./meta.yaml
  Block:
    type: file
    behavior: domain
    path: ./block.yaml  
